### ISSUE TITLE
bitcoin vs bitcoins in plural form

### ISSUE THREAD

**Issue by bolatovumar** [lnbook/lnbook#104]
Both "bitcoin" and "bitcoins" are used in plural form throughout the book. We should decide on a plural form to use going forward. Andreas uses "bitcoin" in the plural in Mastering Bitcoin while Jimmy Song uses "bitcoins" in Programming Bitcoin. Either form is OK as long as it's used consistently.

**Comment by Chriton** [comment]
This topic was discussed here: https://github.com/lnbook/lnbook/pull/43

**Comment by bolatovumar** [comment]
thanks @Chriton. Closing.
