### ISSUE TITLE
bitcoin vs Bitcoin when referring to the network

### ISSUE THREAD

**Issue by bolatovumar** [lnbook/lnbook#106]
Both "Bitcoin" and "bitcoin" are used throughout the book to refer to the overarching Bitcoin network. I propose "Bitcoin" be used consistently to refer to the network while "bitcoin" be used to refer to the currency.

**Comment by Chriton** [comment]
This topic was discussed here: https://github.com/lnbook/lnbook/pull/43

**Comment by bolatovumar** [comment]
@Chriton thanks for pointing this out. Closing this issue for now.
