### ISSUE TITLE
Alice’s First LN Wallet

### ISSUE THREAD

**Issue by ImranLorgat** [lnbook/lnbook#116]
Current CH1 ends with:

`"She also wants a mobile wallet so that she can use it for small payments on-the-go, so she chooses the Eclair wallet, a popular non-custodial mobile LN wallet."
`

Can I take a stab at writing a short guide on setting up an LN Wallet on Eclair for Android, and sending a small payment? And should this go in CH1 or CH2?

**Comment by aantonop** [comment]
I'm already writing that part, will be done over the next 5 days.

I'll be working on chapters 1 and 2, so for now don't do any new PRs.

Once I'm done I'll be needing edits and corrections!

**Comment by ImranLorgat** [comment]
Thanks for the heads up. Didn't want to write something that was being worked on already. I'll take a look when it's done.
