### ISSUE TITLE
iOS Lightning wallets

### ISSUE THREAD

**Issue by ghost** [lnbook/lnbook#120]
The best non-custodial LN wallet for iOS, in my opinion, is Breez. Breez gives you a free 0.01 BTC incoming channel to start with. Sats App & Zeus LN are phenomenal non-custodial iOS LN wallets too. BlueWallet can be non-custodial with the ability to plug-in your own Bitcoin Full node through Electrum Personal Server (EPS), ElectrumX or Electrs.

**Comment by bolatovumar** [comment]
@khny258 Breez Wallet is in the list of LN wallets in Ch. 2 already. See here: https://github.com/lnbook/lnbook/blob/develop/02_getting_started.asciidoc#lightning-wallets

**Comment by aantonop** [comment]
I would like recommendations and reviews of iOS wallets.

* Must be non custodial. We may offer one example of a custodial wallet but we already have BlueWallet that can also be non custodial and works on iOS

* Easy to use, great UX. I prioritize UX over technical features. We may introduce more "advanced" wallets later in the book but for chapter 2 we want a few easy to use options

So far, I've come across:

* Breez
* Peach
* Zap

I can't really evaluate these as I don't use Apple phones

Please add your thoughts and experiences!

**Comment by bolatovumar** [comment]
@aantonop Breez is also available on Android and is the same across both platforms I believe. Zap looks similar but is different across iOS/Android.

**Comment by ghost** [comment]
> I would like recommendations and reviews of iOS wallets.
> 
> * Must be non custodial. We may offer one example of a custodial wallet but we already have BlueWallet that can also be non custodial and works on iOS
> * Easy to use, great UX. I prioritize UX over technical features. We may introduce more "advanced" wallets later in the book but for chapter 2 we want a few easy to use options
> 
> So far, I've come across:
> 
> * Breez
> * Peach
> * Zap
> 
> I can't really evaluate these as I don't use Apple phones
> 
> Please add your thoughts and experiences!

Breez is the best non-custodial LN wallet for iOS, in my opinion. Their UI/UX is unmatched. They also give you a free 0.01 BTC incoming channel to start off with and their support on Telegram is phenomenal. 

Zap is the second best non-custodial LN wallet for iOS. Great UI/UX. Very clean and easy to use but users have to learn about what inbound liquidity is and why it's needed. They must have channels opened to their wallet. 

Peach is a wallet I would not recommend because of their data collection practices. Terrible for privacy!

**Comment by 0xjacobb** [comment]
> I would like recommendations and reviews of iOS wallets.
> 
> * Must be non custodial. We may offer one example of a custodial wallet but we already have BlueWallet that can also be non custodial and works on iOS
> * Easy to use, great UX. I prioritize UX over technical features. We may introduce more "advanced" wallets later in the book but for chapter 2 we want a few easy to use options
> 
> So far, I've come across:
> 
> * Breez
> * Peach
> * Zap
> 
> I can't really evaluate these as I don't use Apple phones
> 
> Please add your thoughts and experiences!

I use Breeze, ZAP, Zeus LN and BlueWallet. My thoughts are:

Zeus is "geeky" and I don't recommend it to "normal users". 

- as per today, Breeze and BlueWallet have more development drive then ZAP and Zeus. 
- The best UI/UX has Breeze and ZAP (both the same in my opinion)
- ZAP is easy to use from external (not only internal network) in combination with mynode over OpenVPN.That's great. Breeze has this feature not until today. The are waiting for [BIP157](https://github.com/bitcoin/bips/blob/master/bip-0157.mediawiki).
- Breeze has key send already implemented, ZAP not but hopefully will follow.

Although, I've started with BlueWallet, which is a great app, Breeze and ZAP are the best way to go on iPhone IMHO. For full "be your own bank style" --> ZAP + mynode.

**Comment by aantonop** [comment]
Does anyone want to tackle a PR to add any missing entries in the table of wallets (Chapter 2)?

**Comment by aantonop** [comment]
Fixed
