### ISSUE TITLE
A few thoughts/suggestions from Chapter 1

### ISSUE THREAD

**Issue by billygarrison** [lnbook/lnbook#131]
> The Lightning Network is not itself a blockchain, nor does it produce a blockchain, it is **a network that relies on existing blockchains** for its security.

This is a bit confusing/misleading, it implies Lightning is a single network that relies on multiple existing blockchains for its security. I understand what is meant, but it doesn't quite convey that. Perhaps rephrase to:

> The Lightning Network is not itself a blockchain, nor does it produce a blockchain, it is **a network protocol that relies on existing blockchains** for its security.

Or:

> The Lightning Network is not itself a blockchain, nor does it produce a blockchain, it is **a network that relies on an existing blockchain** for its security.

(This doesn't imply that it only works for the Bitcoin blockchain)

---

Use of "an LN node": I've seen it mentioned in another comment, but I'd like to reiterate that reading it as "an LN node" feels wrong. It feels very wrong to read it as "an elle-en node". Personally when I see it I read "an LN node" as "an Lightning Network node" or "an Lightning node". For these reasons I think it might be better to use "a Lightning node" or "a Lightning wallet" wherever LN is used.

---

The section "Lightning Network Basic Concepts" uses uppercase items, e.g. "Node" and "Blockchain". The section "Lightning Network Use Cases, Users, and Their Stories" uses lowercase items, e.g. consumer, merchant. It's just a nit, but might want to change it to one or the other for consistency.

---

> Wei has implemented a liquidity provider service that rents inbound channel capacity on the Lightning Network, charging a small bitcoin fee for each rental period.

As an experienced Lightning user, that sentence is a little confusing to me. Is the capacity inbound to Wei's node and he then rents that out for people to use (such as a custodial wallet service)? Or is it inbound to the users? I realize it means it is inbound to the users, but it is somewhat ambiguous and to new readers it will probably go over their heads. It might make sense to simplify it to something like the following:

> Wei has created a service that charges a small bitcoin fee to provide channel liquidity on the Lightning Network.

**Comment by bolatovumar** [comment]
> The Lightning Network is not itself a blockchain, nor does it produce a blockchain, it is **a network that relies on an existing blockchain** for its security.

This looks like the most clear option to me

> but I'd like to reiterate that reading it as "an LN node" feels wrong

This feels alright to me when I read it, "a LN" node seems weird though. I read it as as "ay-elle-en node" which feels weird even though it's not incorrect.

**Comment by aantonop** [comment]
Fixed by c9a5e04c467d0a57190c3ebd5b32474b06c9d43c and f0f78b4f7fd8e16aa8771744c4ec300f8e12ec0d
