### ISSUE TITLE
Copyright of pictures / screenshots / trademarks and logos

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#133]
I have seen that many pictures have been included in chapter two and I want to make sure that we are legally allowed to use them. Should we for example get a written agreement by the folks from ACINQ / Eclair? I am pretty sure they will not mind / object but I guess it is better to just resolve this before problems happen. Similarly the picture of the ATM or the screenshots of the pictures of the cops of coffe. 
Should we have a file somewhere where we keep track of copyright and licences of used pictures?

**Comment by aantonop** [comment]
While these images are almost certainly allowed under the "Fair Use Doctrine" exceptions to copyright, we will get permission from the owners.

[ ] @aantonop Get permission from ACINQ for Eclair screenshots
[ ] @aantonop Get permission from Lamassu for ATM image

**Comment by aantonop** [comment]
[ ] @aantonop Get permission from BTCPay Server team

**Comment by aantonop** [comment]
Added appendix with license notices, with BTCPay MIT license for logo and software images as the starting point 4878d98

**Comment by aantonop** [comment]
[X] Get permission from BTCPay Server team
[X] Ask O'Reilly for copyright release contract
[ ] Get permission from ACINQ for Eclair screenshots
[ ] Get permission from Lamassu for ATM image

**Comment by aantonop** [comment]
Contract created and signed copy received from ACINQ.

Status:
[X] Get permission from BTCPay Server team
[X] Ask O'Reilly for copyright release contract
[X] Get permission from ACINQ for Eclair screenshots
[ ] Get permission from Lamassu for ATM image

**Comment by aantonop** [comment]
[X] Get permission from BTCPay Server team
[X] Ask O'Reilly for copyright release contract
[X] Get permission from ACINQ for Eclair screenshots
[x] Get permission from Lamassu for ATM image

All done!
