### ISSUE TITLE
SPV LN nodes?

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#135]
There is a comment in the text reading: 
```
but there is no "SPV" functionality in the LN peer to peer communication right? they have to have full funcionality?
```
Well you could and eventually might run a LN node without the gossip protocol / BOLT 07. You could then rely on a third party service to make suggestions for path finding and routing. This can even be somewhat decentralized and covered by the protocol in the form of Trampoline routing.

I believe Phonex uses that trick to remove load from the user phone as gossip produces quite some internet traffic which most mobile plans might not support. this can be a privacy issue and protocol improvements for that are still under construction. 

Not sure where and how we include this to the book.

**Comment by aantonop** [comment]
Perhaps this is a good topic for much later in the book. I think when we discuss the "gossip" function and path-finding sections in detail.

**Comment by Roasbeef** [comment]
What you describe above isn't "SPV", and just abuses the term imo @renepickhardt. LN Graph verification is _no where_ as intensive as verifying the entire blockchain. The most expensive part of it is needing to verify that the outputs still exists. Some clients will just skip this step and assume the channels still exist (and were created in the past), which is a minor DoS vector. On our end, we're working on the ability to serve SPV proofs of channel creation over the network, which alleviates some of the burden of initial verification, but doesn't prove that the channels are unspent (something like UTXO commitments are required for that).
