### ISSUE TITLE
Topic suggestion: Lightning Explorers

### ISSUE THREAD

**Issue by 0xmountaintop** [lnbook/lnbook#142]
## What topic should be added? 

Lightning Explorer List

## Who is this topic for [audience]?

Developers, and wallet users.

## Additional context

I wanna add a Lightning Explorer List to the book :

- [1ML](https://1ml.com/) - 1ML explorer (mainnet + testnet)
- [Lightblock](https://lightblock.me) - lightning network explorer mainnet.
- [Lightning network explorer](https://explorer.acinq.co/) - Lightning network explorer (testnet)
- [Robtex Bitcoin Lightning Explorer](https://www.robtex.com/lightning/node/) - Robtex Bitcoin Lightning Explorer (mainnet)

But not sure which chapter it should be placed in?

**Comment by aantonop** [comment]
ACK

**Comment by renepickhardt** [comment]
we should in any case discuss privacy issues with lightning network explorers. For example they might track my IP address and the nodes that I am interested in. 

We should thus emphasize that they just depict information that can already be queried from the gossip protocol and can be seen on the command line or in LAPPS

**Comment by Roasbeef** [comment]
If we end up including this, we need to be very clear that unlike block explorers which show globally verifiable information _objective_, LN explorers are showing _subjective_ information (the info may be out of data, or omit channels which are actually known to exist).

**Comment by aantonop** [comment]
@HAOYUatHZ Please add a section in the node_operations chapter where we discuss 1ml. This would make a great PR!

**Comment by 0xmountaintop** [comment]
> @HAOYUatHZ Please add a section in the node_operations chapter where we discuss 1ml. This would make a great PR!

no problem!

**Comment by 0xmountaintop** [comment]
Hi @aantonop , should I close this issue now?

**Comment by aantonop** [comment]
Yup! Thank you
