### ISSUE TITLE
Topic suggestion: Hardware for Lightning Nodes

### ISSUE THREAD

**Issue by ImranLorgat** [lnbook/lnbook#143]
Note: this is a repost of Issue #128 in the new format

## What topic should be added? ##
Hardware considerations in setting up a self-hosted Lightning Node

I know this book is intended to focus on the Lightning Network protocol and the software that's built around it (e.g. lnd, c-lightning, eclair etc.). However, there's a greater need for hardware knowledge in Lightning than in Bitcoin because:

- Nodes need to be online at all times to receive payment and enforce channel penalties (not so in Bitcoin)

- Channels do not exist on the blockchain, and are only known by the partners. So there is a need for channel backups (e.g. on cloud storage) to prevent loss of funds (only need to backup your seed in Bitcoin)

- If you don't want to rely on custodial services for funding transactions and penalties, you need to run a Bitcoin node and have 200+GB of disk space (and you still need to be your own Lightning Node at least. No 'SPV Lightning' for now)

## Who is this topic for [audience]? ##

Users wishing to host their own Lightning Nodes without relying on custodial wallets, cloud providers, or SPV for Bitcoin transactions

## Additional context ##

So far, most of the user discussion is centered around using Lightning as a user on a mobile. There are users who run their own Bitcoin + Lightning node on dedicated hardware like a Raspberry Pi + Hard Drive. In the future, I can see off-the-shelf Bitcoin+Lightning PoS Terminals being sold to retailers and users. For now, you pretty have much have to build it yourself. Some good open-source examples right now are:

MyNode: https://mynodebtc.com/
Raspiblitz: https://github.com/rootzoll/raspiblitz
Casa Node: https://github.com/Casa (node soon to be open source)

**Comment by aantonop** [comment]
We will be discussing this in two sections:
- Node client (running lnd, c-lightning and Eclair as a server node)
- Node operations (how to operate and maintain your node)

**Comment by Bithandler** [comment]
My apologies if I am incorrect commenting here; what I like, or hope that’s included in this book. I have a lot on my mind being a novice. I think I understand how github works. I like to enact my ignorance through contribution. 

I currently have several Raspberry Pi (all the hardware) needed and never could get any of it to work because most documentation is written above neophyte intelligence. My systems, Mac’s & IOS as [terminal].... I like to follow this process and become your measure.

**Comment by Bithandler** [comment]
I currently have several Raspberry Pi (all the hardware) needed and never could get any of it to work because most documentation is written above neophyte intelligence.  My systems, Mac’s & IOS as [terminal].... I like to follow this process and become your measure.

**Comment by Roasbeef** [comment]
Resources which may be useful for this topic:
  * https://blog.lightning.engineering/posts/2019/08/15/routing-quide-1.html
  * https://blog.lightning.engineering/posts/2019/11/07/routing-guide-2.html
  * https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md

**Comment by ImranLorgat** [comment]
Made an attempt at this in commit #310 so closing this now

@Roasbeef : thanks for sharing the above links. I'll read them, but cannot promise I will understand them 😉
