### ISSUE TITLE
Warning: [role="pagenumrestart"] should only be used in Chapter 1

### ISSUE THREAD

**Issue by aantonop** [lnbook/lnbook#144]
The asciidoc directive:
```
[role="pagenumrestart"]

```

instructs the rendering engine to restart page numbering from "1", which is used to switch from the preface/glossary numbering of "i, ii, iii" in chapter 1. 

This directive *should not be repeated* in subsequent chapters, as that would cause the page numbering to restart from 1 each chapter. Because other chapters have been copied from chapter 1, they erroneously include this directive.

**Comment by renepickhardt** [comment]
ok! I would have not known that. thanks!

**Comment by bolatovumar** [comment]
@aantonop should this directive be removed from Chapter 3 then where it's currently being used? See here: https://github.com/lnbook/lnbook/blob/d44a66d80f2adb75b1488e7cbd03f1468bcea80b/ch03.asciidoc#L1

**Comment by aantonop** [comment]
Fixed
