### ISSUE TITLE
pathfinding vs routing WIP

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#145]
in c299e4577d803ed44646aaff9761f2f14123a19c I tried to introduce the path finding problem. as it is connected to transport / routing I run into some trouble of clear separation. We might have to change the order to start with routing and only discuss path finding as a follow up problem. 

Maybe as path finding is my research topic I am currently making it more complicated as it is. Would still be good to have the discussion and a round or feedback

**Comment by Roasbeef** [comment]
> as it is connected to transport / routing I run into some trouble of clear separation

Is it? It can be presented independent of the transport by first introducing vanilla path finding as an abstract concept using something like Dijkstras. From there, one would then layer on the additional set of constraints like consideration of fees, time locks, min HTLC, etc. Next present the issue with attempting to perform path finding in the forwards direction as typically done. Finally the section can be wrapped up with a high level example which starts from the destination and proceeds to the source with intermediate calculations. A bonus section would then touch on the concept of route hints and advertised vs unadvertised channels. 

If by "routing" you mean onion routing, the above section only needs to introduce the concept of source routing, then a later section can introduce onion routing as an obfuscation technique. Care should be made to accurately outline the privacy gains, and active defenses against deanonymization heuristics.

**Comment by aantonop** [comment]
We have decided to do the order as follows: routing (HTLCs/onions), then channel construction (transactions), then path finding, then gossip etc.
