### ISSUE TITLE
Suggestion: create a To-Do List

### ISSUE THREAD

**Issue by ImranLorgat** [lnbook/lnbook#146]
Hi

Just a suggestion that might make it easier to get more out of your contributors. Perhaps create a to do list of:

- Stubs or topics you want written
- Existing chapters you want expanded or edited
- Specific feedback you're interested in

Right now I'm looking and I'm not really sure where I can contribute and I figure there must be others thinking the same

**Comment by aantonop** [comment]
Thanks @ImranLorgat 

We were already considering how we would do this, but your prompting has doubled our urgency. In the most recent author's meeting, we started working on a more concrete outline for the rest of the chapters, including bullet points for topics and headings. 

Expect a result soon!

**Comment by aantonop** [comment]
README now includes this
