### ISSUE TITLE
Editorial: consistent file naming, 01_... vs ch03_...

### ISSUE THREAD

**Issue by 8go** [lnbook/lnbook#172]
Why do chapter 1 and 2 filenames start with 01_... and 02_... while chapter 3 starts with ch03? If there is no specific reason, please name the files consistently.

**Which part needs editing?**
Filenames

**What editing does this need?**
Rename chapter files to make them consistent

**How does it currently read?**
01_..., 02_..., ch03

**How should it read?**
Have all the chapter files named consistently, e.g. ch01_..., ch02_..., ch03_... etc.

**Comment by Roasbeef** [comment]
Good observation! So we have a few lingering flies that aren't "chaptered" atm, as we're writing drafts which will then be assembled into a final chapter form later on. I'd say chapters 1-3 (ish) are mostly sent content wise, while the later chapters are still in flux. We have a more detailed outline we've created, that'll start to manifest itself as place holder files describing the proposed chapter/section contents, with a series of questions that should be answer in that chapter. It's our hop that this lets new contributors dig in, while seeing the bigger picture, and noting the critical items that should be in the chapter.

**Comment by 8go** [comment]
Not relevant anymore, being adjusted as chapters are written. closed.
