### ISSUE TITLE
Editorial: Simplify headlines, replace acronyms like LN in headlines

### ISSUE THREAD

**Issue by 8go** [lnbook/lnbook#174]
Many headlines contain acronyms. I suggest to replace these acronyms in the headlines wherever possible. I am not talking about the paragraphs, I am just talking about the headlines. 

A book where nearly every single headline has an acronym in it does not seem very user friendly or very readable to me. If someone (e.g. before reading the book) scans the Table of Content, he will be overwhelmed or confused as he finds so many (still unknown) acronyms. Put the acronyms in the text but not in the headers and use acronyms sparingly.

For example, in chapter 2 there are many headlines that contain "LN Wallet", "LN Channel" and similar. I suggest to replace these acronyms in the headlines with "Lightning Wallet", "Lightning Channel". 

**Which part needs editing?**
Many headlines

**What editing does this need?**
Replace acronym with full text, e.g. replace LN with "Lightning"

**How does it currently read?**
e.g. LN Wallets

**How should it read?**
Lightning Wallets

If people like this idea, I can do the changes and submit the corresponding PR. Just let me know.

**Comment by Roasbeef** [comment]
Great points, we've discussed this a bit ourselves as well. However I don't think there's clear consensus at this point, w.r.t which one we're going with (co-authors feel free to correct me here) yet. Myself, I prefer using "Lightning" in most places, as "Lightning Network" is already in the title of the book, and Lightning can be used in most places where "Lightning Network" or "LN" would be applicable.

**Comment by Roasbeef** [comment]
Our weekly meeting is coming up soon, I'll raise this point, then report back, so we can make things consistent now, and have some top level guidelines w.r.t usage.

**Comment by 8go** [comment]
Bringing it up at the weekly meeting is a great idea: please do so.

**Comment by 8go** [comment]
I put in some PRs for this:
PR #270
PR #269
PR #268
PR #267 
PR #266 
PR #265

**Comment by 8go** [comment]
In ch01 thru ch03 this is all corrected with the recent merges. 
Hence, closing this issue.
