### ISSUE TITLE
Editorial: Consistent naming of terms

### ISSUE THREAD

**Issue by 8go** [lnbook/lnbook#175]
All terms should be used consistently. 

In chapter 2 there is a lot of talk about Lightning wallets. These are the terms I found:
- lightning wallet
- Lightning wallet
- LN Wallet

I suggest to always consistently use a single term: e.g. Lightning wallet. (Uppercase L, lowercase w). As in: "Alice is using a Lightning wallet." 

Lightning wallet is just one example. There are many other terms that I have seen used differently in different paragraphs. (Blockchain vs blockchain, etc.)

**Which part needs editing?**
everything needs to be revised

**What editing does this need?**
replace with agreed upon term(s)

**How does it currently read?**
e.g. 
- lightning wallet
- Lightning wallet
- LN Wallet

**How should it read?**
e.g. 
- Lightning wallet

Again, if people think this is a good idea and should be done, then I can start a list, make the agreed upon changes and submit the corresponding PR(s). Just let me know.

**Comment by Roasbeef** [comment]
+1 for "Lightning wallet", I think a PR is welcome here.

**Comment by 8go** [comment]
I have a bunch of PRs outstanding. Once they are pulled, I will create a PR for this.

**Comment by 8go** [comment]
Put in PR for this: see PR #265

**Comment by 8go** [comment]
In chapters ch01 thru ch03 this has been taken care off with the latest merges.
Closing this issue now.
