### ISSUE TITLE
Editorial:  Re-write Categories of LN Wallets in chapter 2

### ISSUE THREAD

**Issue by 8go** [lnbook/lnbook#176]
Chapter 2 has this categorization: 

[[lnwallet-categories]]
.Broad Categories of "LN Wallets"
|===
| Wallet Type          | LN Node        | Keystore/Custody | Technical Skill
| Full Node & Wallet   | Full Node      | Non-Custodial | High
| Non-Custodial Wallet | 3rd-party node | Non-Custodial | Medium
| Custodial Wallet     | 3rd-party node | Custodial     | Low
|===

It is not perfect. It is not ideal. It sort of implies that a "Full Node & Wallet" is not a "Non-Custodial Wallet" because they are 2 different categories. It also states that a "Non-Custodial Wallet" uses "3rd-party node" for LN Node which is not the true definition. In order to simplify, things are getting mixed up here and we are _not_ communicating a clear message. 

The term "Custodial Wallet" is independent of which LN Node is used. 
We should rethink this table and categorization.

**Which part needs editing?**
table Broad Categories of "LN Wallets"

**What editing does this need?**
Correction, clearer distinction, more precise distinction

**How does it currently read?**
see above

**How should it read?**
Here is a first draft, but this might not be perfect either, but at least this draft is consistent:

There are many ways wallets can be characterized or categorized. From all characteristics the two most important criteria are LN Node use and fund custody. Correspondingly the two most important questions to ask about a specific wallet are:
- Does this Lightning wallet have a full LN Node or does it use a 3rd-party LN Node?
- Does this Lightning wallet store its own keys or are the keys held be a 3rd-party custodian?

From these two questions we can derive 4 possible categories. However, the wallet category where a full LN node is used but the keys are held by a custodian is so rare that we ignore it from our discussion. That leaves us with three commonly found categories, but again remember that this is just one way of categorizing Lightning wallets.

[[lnwallet-categories]]
.Three commonly found categories of "LN Wallets"
|===
| Wallet Category    | LN Node        | Keystore/Custody | Technical Skills Required
|===
| Full-Node Non-Custodial Wallet | Full Node      | Non-Custodial | High
| 3rd-Party-Node Non-Custodial Wallet | 3rd-party node | Non-Custodial | Medium
| 3rd-Party-Node Custodial Wallet | 3rd-party node | Custodial     | Low
|===

Sometimes people use the term "Light wallet" as a way to refer to a wallet that does not include a full node. So, when you hear someone talk about a "Light wallet" she or he is referring to a wallet that uses a 3rd-party LN node. A "Light wallet" could be custodial or non-custodial. 

What do you think about that? Ideas? Suggestions? Improvements?
Once the team agrees on something I'd be happy to put it into a PR.

**Comment by 8go** [comment]
I created a PR that covers this. PR #213 
In the PR I suggested to use a Quadrant which seems to be even better than the draft suggested here in the Issue #176.

**Comment by Roasbeef** [comment]
> The term "Custodial Wallet" is independent of which LN Node is used.

Agreed there's a bit more nuance here. At a high level the various categories could look something like:
   * bitcoin data source: full-node, light client (SPV node), 3rd party API
   * key storage: custodial, non-custodial 
   * node status: full routing node, client node 
   * path finding: on device/wallet, delegated to 3rd party 

I'll check out that PR to see how we can start to integrate more of this nuance. As time goes on, a number of hybrid wallet types have also started to emerge that we should catalogue as well.

**Comment by 8go** [comment]
PR merged, issue can be closed.
