### ISSUE TITLE
Create a Network of how the test users are connected

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#186]
for example I imagine that Alice has a channel to Bobs coffee shop who has a chennel to a softare merchant who has a channel to the gamer Gloria. Those seem to be reasonable relations. We migh need others throughout the book and work with them.

**Comment by Roasbeef** [comment]
What do you mean with this issue title? So like introduce this concept early on (this prototypical network structure), then build off of this progressively with more detailed examples?
