### ISSUE TITLE
Topic suggestion:

### ISSUE THREAD

**Issue by aantonop** [lnbook/lnbook#217]
** What topic should be added? **
Running LN clients over TOR

** Who is this topic for [audience]? **
Everyone

**Comment by Roasbeef** [comment]
Potentially useful resource: https://github.com/lightningnetwork/lnd/blob/master/docs/configuring_tor.md

**Comment by renepickhardt** [comment]
c-lightning version: https://github.com/ElementsProject/lightning/blob/master/doc/TOR.md

**Comment by Roasbeef** [comment]
Tor for eclair:
https://github.com/ACINQ/eclair/blob/37c222dce1b6c57685804cea5200d1f8b3620f41/docs/Tor.md

**Comment by aantonop** [comment]
Included in node_operations
