### ISSUE TITLE
Topic suggestion: Routing Node Get @alexbosworth onboard

### ISSUE THREAD

**Issue by HugoDoyon** [lnbook/lnbook#231]
** What topic should be added? **
Routing Node are a key part of Lightning Network, but is still mostly a mysterious beast to discover. 

However, Alex Bosworth is giving us some light on the subject with his tweets. 

Maybe to onboard new user on LN faster we should get Alex onboard for the book 😁 . Summarize his view and experience on the subject in a chapter on routing node (instead of leaving random tweet as legacy).

** Who is this topic for [audience]? **
Audience: Node Operator

** Additional context **
More info: https://twitter.com/alexbosworth

**Comment by aantonop** [comment]
@Roasbeef Can you invite Alex to contribute to the node_operations chapter?

**Comment by Fichte42** [comment]
Absolutely necessarily! @alexbosworth Threadreader unroll :-D

**Comment by renepickhardt** [comment]
has not happend. will close now
