### ISSUE TITLE
Style suggestion: add reference for entries in glossary

### ISSUE THREAD

**Issue by 0xmountaintop** [lnbook/lnbook#232]
What about adding references for glossaries?

for example, we can have 
```
[[BOLT]]
==== BOLT
```
in glossary.asciidoc.

and when we refer to it in node_client.asciidoc we can use `<<BOLT>>`. that can help users
jump to the definitions/explanations quickly and understand the content better.

**Comment by aantonop** [comment]
This is a good idea, but unfortunately it will conflict with the O'Reilly rendering system and cause problems.
