### ISSUE TITLE
Topic suggestion: LNURL

### ISSUE THREAD

**Issue by arcbtc** [lnbook/lnbook#241]
LNURL came out of the trenches of people using LN, and is fast becoming an important part of the network.
It should be covered in the book
https://github.com/btcontract/lnurl-rfc

**Comment by renepickhardt** [comment]
agree in particular as more and more wallets support it

**Comment by arcbtc** [comment]
Its a very powerful technology, which beyond the uses we have seen (LNURL withdraw, pay, auth, channels) can do money streaming, subscription services, offline payment cards, to name a few possible uses. 
Most importantly all in a way that doesn't rely on node software cooperating on adding functionality. 
If anything else it helps inform node implementations, and gather data, on functionality people want, and protocol devs should concentrate on.

**Comment by aantonop** [comment]
@renepickhardt is working on this
