### ISSUE TITLE
Help Me Understand: Preimages

### ISSUE THREAD

**Issue by joshakeman** [lnbook/lnbook#242]
**Which topic needs more explanation?**
The term preimage first appears in chapter three but is only mentioned, not described. 

**What does this topic needs to be easier to understand?**
As a reader who's been through various resources on lightning/bitcoin this word comes up occasionally but is rarely explained. A nice paragraph note about what a preimage is generically and how it effects lightning payments specifically would be very helpful.

**Comment by renepickhardt** [comment]
Have you looked at the routing chapter? Does that help? If so do you think a forward reference in chapter three would be sufficient?

**Comment by joshakeman** [comment]
No I had only gotten through section 3, looks like the topic is well covered in that other section!

**Comment by renepickhardt** [comment]
will close
