### ISSUE TITLE
Help Me Understand: Commitment Transactions

### ISSUE THREAD

**Issue by joshakeman** [lnbook/lnbook#243]
**Which topic needs more explanation?**
In the section explaining commitment transactions there is a multi-step description of building a channel. It references what look like commands like 'accept_channel'

**What about the topic is not understood?**
Since I'd played with the LND command line tool it was confusing for me to see those commands and know they aren't options in the cli

**What does this topic needs to be easier to understand?**
Those commands are apparently inherent to the protocol itself. It may be useful to explain that and differentiate it a bit from user-driven commands like 'sendpayment' or 'addinvoice'

**Comment by renepickhardt** [comment]
I am very sure we have covered this heavily in channel construction by now. will close. feel free to reopen if there are still issues
