### ISSUE TITLE
Emphasize on asymmetric commitment transactions in chapter 03

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#244]
It turns out that readers of chapter 03 how lightning works struggle to know that Alice and Bob need to have different versions of the commitment transaction. 

I believe this is one of the most fundamental and important topics so we should emphasize this better! Currently the relevant passage reads like this: 

> We will now see how such a penalty mechanism can be included to the above construction of the commitment transactions. Usually the commitment transaction has at least two outputs, one for each partner. As new addition, a channel partner will encumber their own output with a timelock and a revocation secret. The timelock prevents the owner of the output to spend it immediately once the commitment transaction was included in a block. The timelock is usually measured in blocktime and can be up to 2016. On average, 2016 blocks represent or last two weeks (assuming a blocktime of 10 minutes as in the Bitcoin network). Within the timelock anyone who knows the revocation secret can spend the output even before the timelock is over. Alice and Bob know only one half each of the revocation secret. But if they share their half with the other channel partner, then the other partner knows the full secret. In order to update the balance and receive a signature from Bob, Alice will have to share her half of the revocation secret of the current commitment transaction with Bob.

**Comment by aantonop** [comment]
I believe this is explained better in Mastering Bitcoin, with a diagram:

https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch12.asciidoc#asymmetric-revocable-commitments

**Comment by renepickhardt** [comment]
I have no doubt about it as we did not do the technical part in it's own chapter. 

BUT: I believe in our high level summery it will be important to stress this particular point (: 

I would prefere a diagram that conains a little bit more information like amounts similar to the one from my presentation. 

cdecker btw uses a stock image of a `lock` image to visualize which outputs are time locked. I always wanted to start doing that too (:

**Comment by renepickhardt** [comment]
think is covered in chapter 07 payment channels
