### ISSUE TITLE
User Story about John the 9 year old painter

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#28]
Merged #25 and as discussed at: https://github.com/lnbook/lnbook/pull/23#discussion_r322012394 this person is very real. We need to figure out if we are allowed to use this story or if it is too close. 

c.f.: https://bitcoinist.com/bitcoin-pictures-lightning-network/

@bitcoina implied in one of his comments that (s)he is a parent of the 9 year old and offered proof that the story may be used. in this case the discussion would be much easier

**Comment by bitcoina** [comment]
you are correct.  will provide proof of approval shortly.  However, we're not precious and while it is a great use case, I don't want to deflect from the educational purpose of the book.

**Comment by renepickhardt** [comment]
I believe this is an extremely nice / neat use case (: by the end of the day we are several authors how will have to find consensus but I personally like it very much (: Also Great work for doing this. best proof would be if you still have access to lightning.pictures to put this message there.

**Comment by aantonop** [comment]
Seems relevant, interesting and appropriate as a user story. Whether it is related to a real person or not does not matter.
