### ISSUE TITLE
Help Me Understand: Convoluted Protocol Breach when you try to cheat the cheater. What happens?

### ISSUE THREAD

**Issue by ImranLorgat** [lnbook/lnbook#306]
**Which topic needs more explanation?**
Channel Close by Protocol Breach

**What about the topic is not understood? - 1**
I'm busy going through this section and a weird corner case popped in my head that isn't likely at all but I'm trying to understand it in any case.

Let's say the following scenario plays out.

1. Alice and Bob open a dual-funded channel with 5 BTC on either side. Channel Balance: Alice 5-5 Bob

2. Alice pays Bob 4 BTC. Channel Balance: Alice 1-9 Bob

3. Bob pays Alice 2 BTC. Channel Balance: Alice 2-7 Bob

Alice cheats! She publishes Commitment Transaction 1 and attempts to finalize the state: Alice 5-5 Bob, essentially stealing 3 BTC from Bob.

Bob catches her, but he publishes the Revocation Secret from Commitment Transaction 2 which finalizes the state as Alice 1 - 9 Bob. But actually the final state was from Commitment Transaction 3: Alice 2-7 Bob.

Technically Bob is stating the final state as 2 more BTC than he actually had, but does it really matter because the channel penalty will give all 10 BTC to Bob in any case?

**What about the topic is not understood? - 2**

And what happens if you try to "cheat" yourself. Same example as above, but now instead Bob cheats! He publishes a Commitment Transaction 1 which states the channel Balance as Alice 5 - 5 Bob. Essentially he is returning 2 BTC to Alice because the final state is Alice 2 - 7 Bob

Can Alice publish the Revocation Secret and take all 10 BTC?

Any of you Lightning Experts understand these bizarre cases 🙂?

**Comment by renepickhardt** [comment]
I think the breach part is coverd. feel free to reopen the issue if it isn't
