### ISSUE TITLE
docker exec command with pipe needs double quotes to run jq in docker instance

### ISSUE THREAD

**Issue by vnprc** [lnbook/lnbook#314]
**Describe the error**
The following command, found in the node_client chapter, fails on my machine because I don't have jq installed locally.
`docker exec bitcoind bitcoin-cli -datadir=/bitcoind getblockchaininfo | jq .blocks`

**To Fix**
To run jq within the docker container you will want to use 'bash -c' and wrap the rest of your command in double quotes like this:
`docker exec bitcoind bash -c "bitcoin-cli -datadir=/bitcoind getblockchaininfo | jq .blocks"`

**Additional context**
If you try with only double quotes the command will fail with this error:
`$ docker exec bitcoind "bitcoin-cli -datadir=/bitcoind getblockchaininfo | jq .blocks"
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"bitcoin-cli -datadir=/bitcoind getblockchaininfo | jq .blocks\": stat bitcoin-cli -datadir=/bitcoind getblockchaininfo | jq .blocks: no such file or directory": unknown`

**Comment by vnprc** [comment]
https://github.com/lnbook/lnbook/pull/319

**Comment by aantonop** [comment]
Fixed by #319
