### ISSUE TITLE
(un)announced channels instead of private/public channels

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#326]
Check that we use the terms (un)announced channels throughout the book as that seems more accurate than public / private channels. Private channels are currently not really private. c.f.: https://github.com/lightningnetwork/lightning-rfc/issues/675

**Comment by aantonop** [comment]
Already addressed in main content, only remaining to fix in glossary. @ImranLorgat has an open PR #389 which will address this

**Comment by renepickhardt** [comment]
PR is merged will close here
