### ISSUE TITLE
discuss port forwarding, nat and tor as a fix

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#358]
**Describe the error**
node operations chapter has a section about running a node from home. 

many people will run into problems because: 
* their router does not forward ports (and we cannot explain this in general)
* their ISPS have dynamic IPs and will change the node's IP address all the time

**To Fix**
Running a local node behind a tor onion helps to mitigate these problems. 

We should thus explain how to do that.

**Additional context**
https://lightning.readthedocs.io/TOR.html

**Comment by aantonop** [comment]
Done
