### ISSUE TITLE
Use of LN as Abbreviation

### ISSUE THREAD

**Issue by nopara73** [lnbook/lnbook#36]
It'll be written million times in the book. Maybe it would make sense to consider to use `LN` consistently instead of `Lightning Network` after the first paragraph.  

Maybe it would be even better done so to use `Lightning Network` in titles and `LN` in bodies.

**Comment by aantonop** [comment]
Agreed. O'Reilly style guide is to associate the acronym to a definition once, then use the acronym. 

LN everywhere after the first paragraph.
