### ISSUE TITLE
Topic suggestion: Weaknesses and Limitations

### ISSUE THREAD

**Issue by 8go** [lnbook/lnbook#373]
** What topic should be added? **
- Weaknesses and Limitations
or maybe 
- Weaknesses and Threads

** Who is this topic for [audience]? **
- Everyone, from noobie to expert

** Additional context **
- General limitation of technology?
  - open to DDOS-like attacks
  - open to partial, limited surveillance
- What to watch out for?
- Thread models?
- Attack vectors?
  - e.g. `Flood and Loot`, see https://medium.com/blockchains-huji/flood-loot-a-systemic-attack-on-the-lightning-network-5c3dac7bba24
- How to protect your node?
- How to protect your channel?
- Standard security advice?
  - Not to open channels with complete strangers

**Comment by renepickhardt** [comment]
I think this is coved in node operation and security / privacy chapter. I will close the comment feel free to reopen if you  ( @8go ) disagree!
