### ISSUE TITLE
Editorial: Change mBTC -> BTC or sats

### ISSUE THREAD

**Issue by ImranLorgat** [lnbook/lnbook#375]
**Which part needs editing?**
Some illustrative examples, such as the channel opening example in chapter 3 and HTLC example in routing chapter, use mBTC to illustrate a point. I find this unit pretty confusing and non intuitive.

1 mBTC = 0.001 BTC or 1000 mBTC = 1 BTC

Not only does this not map to well known fiat currencies paradigms where $1 = 100c, it is also not commonly used by businesses, exchanges, or lightning network software. It is still more common to refer to 50 mBTC as as 0.05 BTC, but can get confusing with decimals. It is becoming more common to refer to 50 mBTC as 5,000,000 satoshis. Many Lightning implementations already encode sats as a base unit for payments and fees, and many Lightning stores denote the cost in sats.

In fact, sats is already used in many examples in the book, such as the tip example in the Gloria chapter. I suggest we make sats the standard through the book and trash mBTC.

**Comment by aantonop** [comment]
We are changing to sats everywhere.
