### ISSUE TITLE
Topic suggestion: The Lightning Channel Graph: topology, attacks and privacy

### ISSUE THREAD

**Issue by seresistvanandras** [lnbook/lnbook#400]
Inspired by a [recent tweet](https://twitter.com/renepickhardt/status/1298918019159207942?s=20) from René (@renepickhardt), it seems it would be great if we could mop up the misconceptions about the privacy of Lightning. To that end, jointly with Carla (@carlaKC), we would be excited to put down a more general and comprehensive chapter on the table which extensively reviews the channel graph not only from a privacy point of view but also from a structural point of view. Payment privacy on LN, among many other things, is largely a topological property. Therefore, it makes sense to give some grounding to this chapter by including purely topological considerations and descriptions of the LN channel graph.

**Please let us know your thoughts and feel free to suggest other sources/potential topics for this chapter!**

** What topic should be added? **
Lightning, in essence, is a network of payment channels. In this chapter, we would like to elaborate more on the network nature of LN from a network scientific point of view. First, we describe LN’s structural properties such as connectivity, centralization etc. Afterwards, we aim to analyze the channel graph’s robustness against topological and other related attacks.  Finally, we consider privacy, an important inherently topological property of LN. 

**1. Topological properties of the channel graph**

- Structure: how does the LN channel graph look like? Even though the graph changes over time, certain properties essentially remain unchanged (e.g. scale-freeness). These defining structural properties have quite some implications for the nature of the graph. 

- Connectivity: how hard is it to route payments in this graph? The small world nature of the graph. Centrality, transitivity of the channel graph. (https://arxiv.org/pdf/1904.10253.pdf,https://arxiv.org/pdf/1901.04972.pdf)

**2. Attacks on the channel graph**

- Robustness: how robust is this graph against failures or targeted attacks?

- More on topological attacks: node isolation, partitioning attacks (https://arxiv.org/pdf/1904.10253.pdf)

- Congestion attacks (https://arxiv.org/pdf/2002.06564.pdf)

- Time-Dilation Attacks on the Lightning Network (https://arxiv.org/pdf/2006.01418.pdf)

- Flood & Loot: A Systemic Attack On The Lightning Network (https://arxiv.org/pdf/2006.08513.pdf)

**3. Payment Privacy in LN**

- LN’s offered privacy guarantees: anonymity set of a node is its degree. The tradeoff between privacy and tx costs. The tradeoff between privacy and the amount of the payment (https://arxiv.org/pdf/1911.09432.pdf).  

- An Empirical Analysis of Privacy in the Lightning Network (https://arxiv.org/pdf/2003.12470.pdf)

- Channel Balance Probing (https://arxiv.org/pdf/2004.00333.pdf)

- Timing attacks on privacy in LN (https://arxiv.org/pdf/2006.12143.pdf)

- Quantitative Analysis of Anonymity in LN (https://eprint.iacr.org/2020/303.pdf)

- Cross-Layer Deanonymization Methods in the Lightning Protocol (https://arxiv.org/pdf/2007.00764.pdf)

** Who is this topic for [audience]? **
Everyone, however we do assume some background knowledge in graph/network theory, but the chapter itself aims to be self-contained as much as possible.

**Comment by s-tikhomirov** [comment]
I think this is a brilliant idea and am willing to collaborate!

Here are a few more more relevant papers that are on my reading list:

* [Toward Active and Passive Confidentiality Attacks On Cryptocurrency Off-Chain Networks](https://arxiv.org/abs/2003.00003)
* [Splitting Payments Locally While Routing Interdimensionally](https://eprint.iacr.org/2020/555) (maybe more relevant for routing part)
* [MAD-HTLC: Because HTLC is Crazy-Cheap to Attack](https://arxiv.org/abs/2006.12031) ([blog post](https://ittayeyal.github.io/2020-06-22-mad-htlc/))
* [Lightning Network: a second path towards centralisation of the Bitcoin economy](https://arxiv.org/abs/2002.02819)

I'd suggest though to center this prospective chapter around LN privacy in general. I suspect more potential readers would like to understand how private are LN payments rather than what topological proprieties the LN graph currently exhibits. That's not to say we shouldn't discuss the graph topology - we should, insofar it helps clarify potential attacks. But would also talk about attacks not directly related to the channel graph.

**Comment by renepickhardt** [comment]
We also believe such a chapter would be of high value and we would be very happy to have this somewhat similar like a survey paper. For us our main focus is currently to get the basics of lightning in an easy to present way done (channel construction / routing / gossip / ...) but an advanced chapter along the lines you suggested would be really great to have but was always seen by as not as much as a "must have" but rather a "really nice to have". So if you guys would help out this would probably become much more realistic.

If you give it a first shot just please make sure to not be too academic in your language as this would be too much of a break and probably be edited out by our editor anyway. 

Could you have an estimate by what time you could have the first version of such a chapter and how many words it might contain? I currently imagine something between 5 to 10 thousand words within a month of time? 

One reminder: When we would want to use diagrams from the quoted papers we have to make sure that the copyright is not violated and that we actually gather permission. Often this can be done by talking to the publishers if they grant us permission and we could do that but would have to know that early enough

**Comment by renepickhardt** [comment]
I think we can close the issue as the PR was merged. Thanks again!
