### ISSUE TITLE
Fix needed: use absolute time references

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#404]
**Describe the error**
The text sometimes contains relative references to time, e.g., in the very beginning of the introduction: "In concept, it's about 5 years old, in implementation about 3 years old". This may not age well.

**To Fix**
Replace with absolute times, e.g.: "the LN was announced in 2015 and launched in 2018."

**Comment by aantonop** [comment]
Hello Sergei!

I noticed you have done a lot of editing work. Thank you!

Would you consider addressing some of these issues with proposed solutions, in the form of pull requests that can be directly merged?

It would be really great help for us if we could merge one PR for each of these issues and fix them quickly.

**Comment by s-tikhomirov** [comment]
Hi @aantonop ! Thank you for your work!

I've been planning to go through the whole book and see where I can contribute most efficiently. I'd rather contribute to a more advanced chapter later in the book rather than smaller editorial issues, which may be the question of taste as well (such as spelling variants). So my priority now is a) to go through the whole book, b) maybe contribute to some later chapter (with a PR), c) address some of the previously opened issues, if time permits.

I understand that fixes are preferable to open issues that may be left hanging around. Going through the next chapters, would it be OK to create just one PR for a bunch of small fixes (in one file), and separate issues for the ones requiring more attention?

**Comment by ImranLorgat** [comment]
When I get some time, I'll offer fixes for a couple of them
