### ISSUE TITLE
Fix needed: block size increase

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#405]
**Describe the error**
In Introduction:

```
However, increasing block size simply shifts the problem to node operators, where each increase in blocksize results in a resource increase multiplied by an order of magnitude.
```

Where does an order of magnitude come from? Is it 2x, 10x? Does it make sense without specifying by how much is the blocksize increased?

**To Fix**
Remove or clarify this point.

Also, the spelling "block size" vs "blocksize" should be consistent.

**Comment by ImranLorgat** [comment]
Related PR:

https://github.com/lnbook/lnbook/pull/438
