### ISSUE TITLE
Fix needed: internet speeds

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#406]
**Describe the error**
In the Introduction:

```
Assuming 250 Bytes on average per transaction this would result in a data stream of 10 Megabyte per second or 80 Mbit/s just to be able to receive all the transactions. This does not include the traffic overhead of forwarding the transaction information to other peers. While single hosts on the internet could handle such a load of traffic our current internet would not be able to support this traffic for a large fraction of hosts.
```

For me, 10 MB/s does not at all seem ludicrous. 5G will be offering up to a gigabit = 120 MB/s, and it is being deployed widely right now.

**To Fix**
Clarify what a "large fraction" would look like. Note that despite the reader may have 10 or 100 or 1000 MB/s at their home, it is not feasible to support such speeds consistently for N computers at the same time (what approximately is N?).

**Comment by ImranLorgat** [comment]
I would comment that it's relative. In South Africa 10 MB/s for one service you're running in the background is pretty ludicrous as 5G and fibre is not widely available here. Data costs are also pretty high here. Definitely not feasible if you want everyone to be able to run a node. Will try to address it in the PR.

**Comment by ImranLorgat** [comment]
https://github.com/lnbook/lnbook/pull/442
