### ISSUE TITLE
Fix needed: trust model of Bitcoin

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#407]
**Describe the error**
In the Introduction:

```
The result would be a network in which only a few users can actually validate the state of the ledger, which ultimately breaks the trust model of Bitcoin.
```

It is not obvious at this point what a trust model is in general, what is the Bitcoin's trust model in particular, and how having only a few validating nodes breaks it.

**To Fix**
Clarify the points above.

**Comment by ImranLorgat** [comment]
Related PR: https://github.com/lnbook/lnbook/pull/443
