### ISSUE TITLE
Fix needed: proper spelling of Tor

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#409]
**Describe the error**
Tor is sometimes spelled "TOR", which [is incorrect](https://support.torproject.org/about/why-is-it-called-tor/).

**To Fix**
Spell Tor as Tor.

**Comment by ImranLorgat** [comment]
Related PR: https://github.com/lnbook/lnbook/pull/444

**Comment by aantonop** [comment]
FYI, there's a way to reference an issue in a PR so that it closes the
issue when merged. I believe you say "Fixes #12345" in the PR title. Please
see if you can use this trick to easily match Issues and PRs and auto-close
the Issues when we fix

**Comment by s-tikhomirov** [comment]
Also FYI, there are more examples of "TOR" in subsequent chapters (may need separate PRs to adhere to the "one PR per file" policy). So I suppose the "fixes" trick shouldn't be used in this particular case, as the spelling should be fixed with multiple PRs for each of the chapters where it's necessary.

**Comment by ImranLorgat** [comment]
> FYI, there's a way to reference an issue in a PR so that it closes the issue when merged. I believe you say "Fixes #12345" in the PR title. Please see if you can use this trick to easily match Issues and PRs and auto-close the Issues when we fix

Noted. Just figured it out!

> Also FYI, there are more examples of "TOR" in subsequent chapters

That's all I found in the intro. For others, might be easier if you submit the PRs yourself. I see them as I go I'll submit something.
