### ISSUE TITLE
Editorial: Bitcoin preserves three properties of money

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#410]
**Which part needs editing?**
Introduction, line 79.

**What editing does this need?**
It is debatable whether Bitcoin has all three properties (to the full extent). SoV narrative is strong, but I suspect most people still perceive it as a very volatile asset. As of UoA, is it really used to quote prices by anyone except enthusiasts and exchanges?

**How does it currently read?**
"As an electronic cash system, Bitcoin preserves the three most important properties of money (medium of exchange, store of value, and unit of account)."

**How should it read?**
Something along the lines of: Bitcoin has the three properties to various extent, it is already a MoE, and as it gets more popular, we expect it being used as SoV and UoA more widely.

**Comment by ImranLorgat** [comment]
Hmmm.... not 100% sure about this one

Definitely still a volatile asset, and not a useful UoA for general consumer purchases, but on the Lightning Network sats are actually the unit of account for fees and invoices. And on the Bitcoin network fees are priced in sats per byte. Retail goods are usually priced in USD and then converted to sats I suppose as well. 

Hmm... not sure how to address this simply without getting into economic questions
