### ISSUE TITLE
Editorial: "wallet" functionality

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#412]
**Which part needs editing?**
Chapter 2 (Getting started)

**What editing does this need?**
The sentence may read a bit strange for a novice: isn't sending and receiving payments exactly what a node is supposed to do? Why is this separated into a "functionality", as if having a node without this functionality would make sense?

**How does it currently read?**
"Nodes also include "wallet" functionality, so they can send and receive payments over the Lightning Network as well as on the Bitcoin network."

**How should it read?**
Maybe replace "wallet" with "keystore" - a term used later? (And clarify what it does)

**Comment by ImranLorgat** [comment]
Hmmm... not sure about this one. I kind of like the paragraph in its current state. It elucidates the the three functions of a node.

Also I like wallet > keystore

**Comment by s-tikhomirov** [comment]
I'm not opposed to the structure, rather, I'd like to see a more detailed explanation of what the wallet does (stores the keys, signs transactions, keeps track of balances...).
