### ISSUE TITLE
Help Me Understand: What is a BIP?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#417]
**Which topic needs more explanation?**
Chapter 2 makes a casual reference to BIPs:

```
Neutrino is a specific implementation of a protocol to get data from Bitcoin as outlined in BIP 157 and BIP 158.
```

**What about the topic is not understood?**
What does it mean to get data "from Bitcoin"? What is a BIP and what to the numbers 157 and 158 mean?

**What does this topic needs to be easier to understand?**
Explain that there may be different ways - protocols - to get the information on the current state of the Bitcoin blockchain, and they involve different trade-offs (privacy, etc). Neutrino is one of such protocols. Links to BIPs may be moved to a footnote or a reference.

**Comment by ImranLorgat** [comment]
I agree that sentence could be worded more clearly. BIPs are defined in the glossary. The reader is also assumed to have casual knowledge of Mastering Bitcoin
