### ISSUE TITLE
Help Me Understand: What is Electrum?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#418]
**Which topic needs more explanation?**
Chapter 2 - Getting started:

```
Electrum: This means the wallet connects to an Electrum Server. The Bitcoin Node is run by a third-party and accessed via the  "Electrum" protocol.
```

**What about the topic is not understood?**
What is Electrum - a protocol, a piece of software, a company? How is accessing a Bitcoin node via the Electrum protocol different from... the regular way of doing this? What is an Electrum server, who runs it? Is there only one server or many such servers, how do I choose one, or does my wallet choose one automatically, how?

**What does this topic needs to be easier to understand?**
Something along the lines of: Electrum is a separate network designed for faster access to the Bitcoin blockchain, Electrum nodes are ran by (whom?), with Electrum you trade-off speed for privacy, Electrum may be beneficial for an LN node, because (reasons).

**Comment by quantumcthulhu** [comment]
There are Electrum client (GUI app) and Electrum Server (actually it is called ElectrumX).

Electrum Server connects to the Bitcoin Core node and builds its own database, matching each unique address (actually each unique hash of an output script) to a list of transactions. 

Electrum client connects to an Electrum Server via Electrum protocol. Anyone can run an Electrum Server, there are many of them, you can run your own and connect only to it for security reasons. 
By default Electrum client connects to a bunch of Electrum Servers to ask their block heights, then it reveals it's master pubkey to a randomly chosen Electrum Server with max block height. That Electrum Server returns a list of transactions bound to the addresses derived from the master pubkey.
