### ISSUE TITLE
Editorial: a static tip address is bad privacy practice

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#421]
**Which part needs editing?**
Chapter 2, line 251 advocates for using a static Bitcoin address for tips. It seems like a bad practice privacy-wise: everyone would be able to link the address with Alice's identity and track all her future payments (not even mentioning the [dust payments](https://www.coindesk.com/dust-attacks-bitcoin-wallets) and whatever nasty techniques chain analysis firms invent).

**What editing does this need?**
Remove this scenario or mention the drawbacks of this practice.

**How does it currently read?**
"Alice could even print the QR code and affix it to a sign and display it publicly to receive tips. For example, she could have a QR code affixed to her guitar and receive tips while performing on the street!"

**Comment by ImranLorgat** [comment]
Hmm... I agree. Reusing addresses is a bad idea but unfortunately Bitcoin does not have an easy workaround for receiving payments in a public setting like this without reusing addresses. Just going to PR a footnote to explain that this isn't advised.
