### ISSUE TITLE
Editorial: six confirmations

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#426]
**Which part needs editing?**
In chapter 2, Alice waits for 6 confirmations when opening a channel. Doesn't this depend on the amount and the willingness to take risk? Or is it enforced by the LN protocol? Or by Eclair? Can Alice start using the channel after 1 confirmation if she chooses so?

**What editing does this need?**
Explain what the number of confirmations mean and who decides how many is enough. Also, it may not be obvious that "confirmation" = "blocks built on top of the block that included the funding transaction, including that block".

**How does it currently read?**
While Eclair will detect the bitcoin transaction in just a few seconds, it will take approximately one hour for the bitcoin transaction to be "confirmed" on the Bitcoin blockchain. As you can see in <<eclair-tx1>>, Alice's Eclair wallet shows "6+ conf" below the transaction, indicating that the transaction has received the required minimum of six confirmations, and her funds are now ready to use.

**Comment by ImranLorgat** [comment]
I believe this is specified in BOLT 2 via the `minimum_depth` parameter. I don't recall seeing it discussed anywhere. This is a good suggestion for the chapter on channel construction which is a WIP at this point.

https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#channel-establishment
