### ISSUE TITLE
Editorial: introduce Bitcoin's monetary units

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#433]
**Which part needs editing?**
The book uses Bitcoin's monetary units (satoshis, mBTC) without much explanation.

**What editing does this need?**
Add a note in one of the first chapter explaining what satoshi / mBTC is. Use the units consistently throughout (e.g., unify plural spelling: satoshi(s), bitcoin(s)).

**Comment by ImranLorgat** [comment]
I've proposed scrapping mBTC entirely and just focusing on BTC and sats

https://github.com/lnbook/lnbook/issues/375

#MakeSatsTheStandard
