### ISSUE TITLE
Editorial: Why is trust bad?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#434]
**Which part needs editing?**
Cryptocurrency folks are used to the term "trusted" implying "bad" and "trustless" implying "good". I suspect for most regular people it is the other way around: "trustless" is "something that shouldn't be trusted", whereas "trusted" is "reliable". For example, consider the phrase "channel partners do not have to trust each other". Why would I enter a partnership with someone I don't trust, one may ask?

**What editing does this need?**
When talking about how LN / Bitcoin doesn't require trust, exemplify / contrast it with centralized banking. What does it mean to trust a third party? Why is trust a bad thing in monetary protocols?

**Comment by ImranLorgat** [comment]
Hmm... would probably make for a good inclusion in the intro. There's a famous Nick Szabo quote: "Trusted third parties are security holes". But, of course, not intuitive for those entering the space for the first time. 

I note there is actually some discussion on trust and trust minimization in Ch2. See the link below.

https://github.com/lnbook/lnbook/blob/develop/02_getting_started.asciidoc#lightning-wallets
