### ISSUE TITLE
Help Me Understand: Why not cheat if I have nothing to lose?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#435]
**Which topic needs more explanation?**
The LN's incentive mechanism discourages cheating by allowing the other party to take all the funds from the channel. But what prevents Alice from depleting a channel with Bob completely and then trying to cheat? If Bob notices it, he takes all the funds from the channel, but Alice would not lose anything (her balance is zero or near-zero). If Bob doesn't notice, Alice wins big. Seems like cheating is a rational strategy here.

**What about the topic is not understood?**
How does the LN address this issue?

**What does this topic needs to be easier to understand?**
More explanation on the "skin in the game" in LN channels: how much does a cheater actually risk, what does it depend on?

**Comment by ImranLorgat** [comment]
This is actually a really good point. Open a channel, spend all the money, then try to cheat. What have you got to lose.

Might even be worth posting to the LN Devs and seeing what they say.
