### ISSUE TITLE
Help Me Understand: how is a payment secret generated and shared?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#437]
**Which topic needs more explanation?**
In Chapter 3:

```
The two channel partners hold half of the revocation secret, so that neither one knows the whole secret. If they share their half, then the other channel partner has the full secret and can use it to exercise the revocation condition. When signing a new commitment transaction, they revoke the previous commitment by exchanging the signature for the revocation secret.
```

**What about the topic is not understood?**
First, who generates the secret? If it is one party, isn't it at an unfair advantage? If the two parties generate the secret collaboratively, how does this work? Also, why do they exchange the _signature for the revocation secret_, not the secret itself? How can one derive the secret from the signature?

**What does this topic needs to be easier to understand?**
Explain the secret generation and exchange in a bit more detail. Emphasize that no party has an advantage over the other (noone gets the secret earlier than the other, etc).

**Comment by renepickhardt** [comment]
it't the secret as described in https://github.com/lnbook/lnbook/blob/develop/channel-operation.asciidoc via the revoke and ack
