### ISSUE TITLE
Help Me Understand: who signs a commitment transaction first?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#439]
**Which topic needs more explanation?**
In Chapter 3:

```
Alice signs Bob's new commitment transaction only if Bob offers his half of the revocation secret for the previous commitment. Bob only signs Alice's new commitment transaction if she gives him her half of the revocation secret from the previous commitment.
```

**What about the topic is not understood?**
What if Bob gives his half of the revocation secret to Alice, but Alice refuses to sign the next commitment transaction? Can't Alice just take all coins from the channel at this point?

**What does this topic needs to be easier to understand?**
Explain step by step, who sends what in what order and why there is exactly one valid pair of commitment transactions at any point (if it's true, of course).

**Comment by aantonop** [comment]
This is explained in detail in a subsequent chapter and not here. We go through the protocol messages step by step.
