### ISSUE TITLE
Help Me Understand: How are in-flight HTLCs resolved on mutual close?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#445]
**Which topic needs more explanation?**
In Chapter 3, describing "the good way" to close a channel:

```
No new routing attempts will be accepted from either channel partner and any ongoing routing attempts will be settled or removed after they time-out. Finalizing the routing attempts takes time, so a mutual close can also take some time to complete.
```

**What about the topic is not understood?**
How much time can this take? How does this look like from the point of view of the users who started routing through this channel? Say, there is an ongoing payment Alice - Bob - Charlie - Dave. Then Bob decides to close a payment with Charlie. Will Dave be able to complete the payment?

**What does this topic needs to be easier to understand?**
Clarify how "finalization" is implemented, and does it imply failing the in-flight payment.

**Comment by aantonop** [comment]
These details form the basis of an entire "routing" chapter (likely to be chapter 6). Chapter 3 is too early to go into this detail.
