### ISSUE TITLE
Editorial: what is a "well maintained" LN node?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#448]
**Which part needs editing?**
In Chapter 3:

> properly maintained Lightning node

> it is just as easy to keep a well maintained node running continuously

**What editing does this need?**
What is "maintaining" a node? From what has been described earlier it may look trivial: put some coins in some channels and leave it running. What does the art of maintaining a node entail?

Also, I'd disagree that it is "just as easy" to keep a node running as opposed to turning it on and off time to time. Not everyone is familiar with cloud services, and running a node 24/7 on a regular computer is simply inconvenient (noise, heat, electricity consumption).

**Comment by aantonop** [comment]
Chapter 5 "node_operations" covers this topic in detail.
