### ISSUE TITLE
Editorial: is a channel announcement forwarded only once?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#452]
**Which part needs editing?**
Chapter 3 states that each channel announcement is only forwarded if it had not been forwarded by this node earlier.

**What editing does this need?**
Does this mean that a node forwards a channel announcement at most once, even if it is connected to multiple nodes? This differs from Bitcoin's P2P layer where a transaction is forwarded to all (?) neighboring nodes, probably after random delays. This point needs clarification.

**How does it currently read?**
In order to avoid excessive communication the channel announcement is only forwarded by each node if it has not already forwarded that announcement previously.

**Comment by renepickhardt** [comment]
I think that is too detailed for the book and should be read upon on the BOLTs our gossip chapter is already one of the most technical ones. I will close this but feel free to reopen if you disagree.
