### ISSUE TITLE
Editorial: clarify terminology: multi-PATH or multi-PART payments?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#455]
**Which part needs editing?**
Chapter 3:

> With technologies such as Atomic Multi-Path (AMP) and Multi-Path Payments (MPP)

**What editing does this need?**
Are these the same thing or different things? I've also heard that multi-_path_ has been "renamed" to multi-_part_, but I'm not why and what is the difference (I remember listening to [this episode with Rusty Russel](https://stephanlivera.com/episode/134/) of the Stephan Livera podcast, but has already forgotten what's the deal with part vs path there). This terminology should be clarified / updated.

**How does it currently read?**
With technologies such as Atomic Multi-Path (AMP) and Multi-Path Payments (MPP), which we will review in subsequent chapters, several Lightning paths can be aggregated into a single atomic payment

**Comment by renepickhardt** [comment]
related to #397 which is still open thus I will close this one.
