### ISSUE TITLE
Help Me Understand: Why don't Bitcoin miners charge fees proportional to transaction value?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#457]
**Which topic needs more explanation?**
It is correctly stated that Bitcoin transactions pay fees proportional to their weight, whereas fees in LN are related to value.

**What about the topic is not understood?**
Why don't Bitcoin miners try to charge higher fees for high-value transactions? It is well-known that i.e. airplane tickets are sold at a higher price to buyers from richer countries - that is, sellers are leveraging any information about the buyer's potential willingness / ability to pay to charge (ideally) the maximum amount they can get away with. Why isn't this happening with Bitcoin transaction? It should be obvious for a miner that someone moving $1m is probably ready to pay $100 for the service.

**Comment by ImranLorgat** [comment]
This is already addressed in Ch3, how LN Works. There's a subsection at the bottom that is a comparison to Bitcoin. 

https://github.com/lnbook/lnbook/blob/develop/03_how_ln_works.asciidoc#varying-fees-depending-traffic-vs-announced-fees

**Comment by s-tikhomirov** [comment]
Chapter 3 does not exactly answer my question. I understand that the scarce resource on-chain is the transaction weight. I fail to grasp why miners don't leverage their knowledge about transaction value to extract more fees. A real-world analogy: if you come to a market wearing an expensive suit and a gold watch, expect the sellers to quote higher prices to you, as compared to poorer-looking folks.

**Comment by ImranLorgat** [comment]
Hmm... now we're getting into block space and fee market dynamics which is probably beyond the scope of the book

Simply put, miners are only constrained in terms of the block space they can produce: approx 1MB per block excluding witnesses (4000 weight). They only benefit from fees. Let's say there are 3 transactions:

1. Send 1 BTC with a fee of 0.02 BTC (fee 2%)
2. Send 2 BTC with a fee of 0.02 BTC (fee 1%)
3. Send 0.2 BTC with a fee of 0.01 BTC (fee 5%)

The first two are identical to them. It makes no difference what the value transacted is. The third, while having a higher fee as a % of transaction is still lower income to them. If they refuse to mine 2 on the principle that it pays the lowest fee as a % of transaction, someone else will just come along and mine it!

**Comment by s-tikhomirov** [comment]
I agree that this may be outside of scope, just something that I find strange about the fee market in general.

> If they refuse to mine 2 on the principle that it pays the lowest fee as a % of transaction, someone else will just come along and mine it!

It's not so much on principle but rather in a rational attempt to extract higher fees from large transactions. If I'm a miner, it seems rational to me to choose transaction 1 instead of transaction 2 if I have to choose one. My hope would be that the sender of transaction 2 will raise the fee, and there is more "space" to do it because the transaction amount is higher.

**Comment by PatrickZGW** [comment]
> My hope would be that the sender of transaction 2 will raise the fee, and there is more "space" to do it because the transaction amount is higher.

Why should they raise the fee, if another miner will just include the transaction for them? What you are suggesting would only work if miners colluded, but if that happens we have bigger problems than the fee market.

> A real-world analogy: if you come to a market wearing an expensive suit and a gold watch, expect the sellers to quote higher prices to you, as compared to poorer-looking folks.

This does not happen in a competitive market like mining. If someone tries to raise the price on you, you can just go to another seller. Same reason why supermarkets don't charge more for the same item, no matter how rich you are.

**Comment by renepickhardt** [comment]
I think it is just outside the scope of the book
