### ISSUE TITLE
Fix needed: glossary: payment channels

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#463]
**Describe the error**
This glossary entry refers to previous work on payment channels:

```
There are currently three methods known to construct a fully duplex bidirectional payment channel.
    Christian Decker proposed a method in his PhD thesis based on invalidation trees.
    In the Lightning Network whitepaper, Joseph Poon and Tadge Dryja describe the Revocable Sequence Maturity Contract based method that is currently being implemented on the Lightning Network.
    Recently Christian Decker et al. came up with the Eltoo mechanism which would require a Bitcoin softfork.
```

**To Fix**
A few suggestions:

* clarify that "a method based on invalidation trees" is the same as "Duplex channels", mentioned in the book previously.
* does a glossary entry even need such a detailed account of all existing constructions?
* if it does, Christian Decker's co-authors should probably also be mentioned (both Duplex and Eltoo papers have multiple authors)
* I'd rather suggest that the author names and details be omitted for brevity, and provided as footnotes or references: "there are three constructions: Duplex [1], Lightning [2], and eltoo [3]".
* aren't there more than three payment channel constructions? One could argue that the fourth one is [Spillman channels](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2013-April/002433.html), [implemented in BitcoinJ](https://bitcoinj.github.io/working-with-micropayments)). And the initial Satoshi's proposal (based on `nLockTime`, not enforceable) count?

**Comment by ImranLorgat** [comment]
Bizarrely, the glossary contains definitions for both _payment channels_ and _payment channel_

I agree with your second point that the above definition is way too complex for a quick glossary. Best left for the section on channel construction.

I've proposed a much simpler formulation in the pull request below.
