### ISSUE TITLE
Editorial: Use alphabetical placeholder names in examples

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#464]
**Which part needs editing?**
The routing chapter goes somewhat against the [convention](https://en.wikipedia.org/wiki/Alice_and_Bob) by using the placeholder names that do not start with the first letters of the alphabet: Alice - Bob - Wei - Gloria. The reader may have to switch back and forth between the schemes and the text to remember whether e.g. Wei comes before or after Gloria.

**What editing does this need?**
Use standard alphabetical names (e.g. Alice - Bob - Charlie - David).

**Comment by ImranLorgat** [comment]
These are characters @aantonop came up with in the intro below. They have personas and back stories. He used a similar approach in Mastering Bitcoin

https://github.com/lnbook/lnbook/blob/develop/01_introduction.asciidoc#lightning-network-use-cases-users-and-their-stories

**Comment by aantonop** [comment]
Then again, this might not be the best approach. We could come up with diverse names and stories by still keep them alphabetically sorted. @s-tikhomirov is right. Better change it sooner rather than later.

@renepickhardt @Roasbeef Thoughts?
