### ISSUE TITLE
Help Me Understand: What's remarkable about changing value for a preimage?

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#465]
**Which topic needs more explanation?**
In the routing chapter:

> Isn't it remarkable that even though the process of exchanging funds for an preimage seems to be happening concurrently at the same moment in time in reality it is actually happening one step after another but in the right order.

**What about the topic is not understood?**
I'm not sure I get this point. Yes, from a higher level of abstraction value is exchanged for a preimage as a single atomic step. From the implementation perspective, it consists of multiple steps. One could similarly say: isn't it remarkable that a web page is rendered at the same I type the URL and press enter, whereas there are multiple HTTP requests and responses going on under the hood? Isn't this how multi-layered protocols work generally?

**Comment by renepickhardt** [comment]
I think it is just style and might be removed in final editing. will close this for now.
