### ISSUE TITLE
Fix needed: define ephemeral key in routing chapter

### ISSUE THREAD

**Issue by s-tikhomirov** [lnbook/lnbook#466]
**Describe the error**
The term "ephemeral key" appears in the routing chapter without much explanation:

> Let `(d,D)` be the secret and Public key of David and let G be the generator point of the elliptic curve so that `D = d*G`.
Similarly let `(ek_d, EPK_D)` the ephemeral keys that Alice has generated for David such that the Public ephemeral Key `EPK_D = ek_d*G`.

**To Fix**
Explain briefly what an ephemeral key is and why it is needed in the routing process.

**Additional context**
There is a corresponding entry in the glossary, but a) it probably would be more convenient for the reader to get the general intuition right where it is needed (in the routing chapter); b) the glossary entry may also need improvement (see also #462).

**Comment by misbach** [comment]
The first time ephemeral key is used is now on line 484, and states:

> Taking a step back, before Alice is able to prepare the remainder of the packet, we need to generate an ephemeral key (a key only used once). This ephemeral key is then used to generate a series of additional keys, which are themselves used for encryption, authentication, and also as input to a CSPRNG to deterministically generate the set of random filler bytes.

@s-tikhomirov Do you think this is sufficient?

**Comment by s-tikhomirov** [comment]
Looks good, though from this description it's not clear if these keys are public vs private (they are actually key _pairs_, may be worth speling this out). Also,

> This ephemeral key is then used to generate a series of additional keys

Are these additional keys also called ephemeral keys?

Overall, I think that the way ephemeral keys are introduced now does make more sense then previously, but I can't judge if it's sufficient without re-reading the chapter.

**Comment by renepickhardt** [comment]
I think it is now explained in detail in the routing chapter (even though the term ephemeral is only used twice there)
