### ISSUE TITLE
Help Me Understand: Spelling standard for contribution

### ISSUE THREAD

**Issue by carlaKC** [lnbook/lnbook#537]
**Which topic needs more explanation?**
If looking to contribute, it is unclear whether US or UK spelling should be used (canceled/cancelled, colour/color etc)
(the great divide of our time, long live UK spelling, long live)

**What about the topic is not understood?**
Which spelling standard to use. 

**What does this topic needs to be easier to understand?**
Add preferred spelling standard to contribution guidelines.

**Comment by aantonop** [comment]
We should use US spelling.
