### ISSUE TITLE
Why use GOPATH if using module-aware Go version?

### ISSUE THREAD

**Issue by ysangkok** [lnbook/lnbook#561]
**Describe the error**
I noticed that the code examples rely on `GOPATH`, and I wonder if the instructions couldn't be made simpler using `go get`. That way, lnd could be downloaded without git, and it would be faster since the whole git history wouldn't need fetching

**To Fix**
[go install](https://golang.org/cmd/go/#hdr-Compile_and_install_packages_and_dependencies)

**Additional context**
Alternatively, the fetching of the whole git history could be avoided by downloading master.zip, since Github will automatically generate zip files for every repo.

**Comment by aantonop** [comment]
I'm not a Go expert. Can you please suggest a fix with a pull request?

**Comment by ysangkok** [comment]
let me first ask @Roasbeef if he thinks it would make sense. Roasbeef, do you think it would be better to avoid `GOPATH`? installation with `go get`/`go install` or `git`? i guess maybe git should be retained since the installation instructions assume people may want to hack on lnd.

**Comment by aantonop** [comment]
Already fixed by @motorina0 in a previous pull request!
