### ISSUE TITLE
Eclair command output logs outdated

### ISSUE THREAD

**Issue by ysangkok** [lnbook/lnbook#562]
**Describe the error**
The command line logs for eclair are really old since they mention version 2.13, but the current version is 0.4.2. The command line logs mention the GUI, which was removed. This could mislead the reader into thinking that eclair should build with a GUI, while that will never be the case at publication time.

**To Fix**
The commands should be rerun and current output should be inserted.

**Comment by aantonop** [comment]
We have a new version pushed now. Would you consider running the examples and submitting the correct logs in the chapter as a pull request, @ysangkok ?

**Comment by ysangkok** [comment]
Yes! I will have a PR ready during this weekend.
