### ISSUE TITLE
Fix needed [Typo, Grammar, Syntax, Terminology, Spelling, Fact, Code]

### ISSUE THREAD

**Issue by Scott-Driscoll** [lnbook/lnbook#572]
**Describe the error**
Incorrect words used

**To Fix**
In Routing chapter:
"In addition to this forwarding rate, Alice also needs to be ~~conceded~~ **concerned** about what time locks to use."

"Instead, **the** answer to the second question has a very large solution space, meaning there are several algorithms and ~~neuritics~~ **heuristics** used in the network today." (wasn't able to find anything by googling "neuritics", may just be my unfamiliarity)

"~~Lets~~ **Let's** stick to our example in which Alice still wants to tip Gloria and has decided to use the path via Bob and Wei."

**Comment by misbach** [comment]
@Scott-Driscoll PR #659 has been approved and merged. Do you mind verifying it fixes this issue and closing this issue?
