### ISSUE TITLE
Fix needed [Dockerfile c-lightning]

### ISSUE THREAD

**Issue by norisg** [lnbook/lnbook#574]
**Describe the error**
Docker cannot build images because the base-image (lnbook/bitcoind) changed from 18.04 to 20.04 therefore we also need to change this here. But I am not really in line with the solution of a fixed version, I prefer to go without it.

**To Fix**
Dockerimage for c-lightning builds when replacing the line in the Dockerfile with the following:
ENV C_LIGHTNING_VER	0.9.2~0~ubuntu20.04.1

**Comment by keblek** [comment]
#640  Handles this

**Comment by norisg** [comment]
will close this issue in favour of #640, thanks @keblek
