### ISSUE TITLE
Editorial: New Chapter - Bitcoin Fundamentals Review

### ISSUE THREAD

**Issue by aantonop** [lnbook/lnbook#584]
Our initial tech review has brought up a point that we have been discussing internally: 

How much of "Bitcoin Review" do we need in this book. We considered making "Mastering Bitcoin" a prerequisite to this book and that does not seem like a good solution. Even though it is available for free, it seems wrong to ask people to go read another book before reading this one. 

Therefore, I am proposing that we add a chapter that offers a quick review of Bitcoin's most important features and concepts that relate to the Lightning Network. Specifically, the chapter should cover

* [ ] Bitcoin transactions (inputs / outputs)
* [ ] Transaction chaining (UTXO, TxID references)
* [ ] Bitcoin Script - Locking/Unlocking scripts
* [ ] Common scripts (P2WPKH, K-of-N Multisig)
* [ ] Complex scripts (overview of conditional script statements - IF ELSE)
* [ ] Timelocks
* [ ] Hash functions

Most of this will be pulled from Mastering Bitcoin, but re-written in less depth and related to Lightning. The chapter will likely be inserted somewhere in the first 5 chapters.

**Comment by ImranLorgat** [comment]
Good idea. If you can pull something rough together, happy to help with the editing, flow, and composition.

**Comment by renepickhardt** [comment]
and let us explicitely not forget segwit. I understand it is the W ind P2WPKH I am just mentioning it (:
