### ISSUE TITLE
adding online video resources

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#59]
I added a video by using the asciidoc TIP style. I thought it would be neat if we had a MEDIA style for such videos. will that be possible?

**Comment by vv01f** [comment]
currently to be found in [history](https://github.com/lnbook/lnbook/blame/b4d767577fcab03cde0f370557c946c6290ed61e/contrib/history.asciidoc#L64)

I'd expect O'Reilly to have constraints for their production

basically that is possible, how depends heavily on the build system
e.g. in epub http://idpf.org/epub/301/spec/epub-publications.html#sec-resource-locations

asciidoc can support videos e.g. this way: https://asciidoctor.org/docs/user-manual/#video

also consider high-availability for linked content (youtube channels might be depublicised) and what and how much media in total (conservative estimate for file size limitations of formats and devices) you want to include or fall back on linking to external resources
possible constraints: the print version should link and show a picture, ebooks may include image/audio/video if their standard (e.g. ibooks/epub, mobi do so) supports it, at least a source/link should be referenced with usability in mind (e.g. resources on the git and list of media – may as well be a good place for attribution – as annex)

**Comment by aantonop** [comment]
Not possible with the current build system and pipeline. @renepickhardt will have to add short links in footnotes.
