### ISSUE TITLE
Editorial: Consider replacing "Wei" nomenclature

### ISSUE THREAD

**Issue by AndrejMitrovic** [lnbook/lnbook#590]
**Which part needs editing?**

https://github.com/lnbook/lnbook/blob/develop/routing.asciidoc

**What editing does this need?**

Replace "Wei" with "Charlie" or with any other name that happens to start with a letter somewhere between Bob and David / Gloria.

The reasoning I have for this is it makes the names sorted alphabetically, which makes it easier to track the "hop index" in the payment channel. Right now it reads "alice, bob, wei, david", and it's hard to memorize that "wei" is the 3rd hop. It would be much easier if it was Charlie or Chris / Christina, or something similar. E.g. Alice / Bob / Charlie / David. 

-----

Also the graphs are showing Gloria as the destination node even though the text refers to it as David. Should I file another issue?

**Comment by keblek** [comment]
#517
