### ISSUE TITLE
Fix needed [renegade a signed contract should be renege on a signed contract]

### ISSUE THREAD

**Issue by Giszpenc** [lnbook/lnbook#624]
**Describe the error**
https://github.com/lnbook/lnbook/blob/develop/contrib/history.asciidoc uses the wrong word.  The following phrase is wrong:
 if a party attempts to renegade a signed contract, they lose all their funds!

**To Fix**
if a party attempts to renege on a signed contract, they lose all their funds!

**Additional context**
none

**Comment by misbach** [comment]
@Giszpenc PR #659 has been approved and merged. Do you mind verifying it fixes this issue and closing this issue?
