### ISSUE TITLE
Fix needed [Image links to 404]

### ISSUE THREAD

**Issue by AndrejMitrovic** [lnbook/lnbook#635]
**Describe the error**
In https://github.com/lnbook/lnbook/blob/develop/routing.asciidoc#routing-a-payment the link to https://github.com/lnbook/lnbook/blob/develop/images/dina-routing-diagram.PNG is a 404.

**Comment by misbach** [comment]
@AndrejMitrovic I fixed this in pull request #659. Do you mind verifying it's fixed and then closing this issue?

**Comment by AndrejMitrovic** [comment]
Looks good! Thank you!
