### ISSUE TITLE
Fix needed [Image missing, confusing sentence]

### ISSUE THREAD

**Issue by giovannizotta** [lnbook/lnbook#655]
**Describe the error**
Routing chapter (routing.asciidoc) on line 30: the image is missing. 
Also, while reading I was confused by lines 25-26: who is Glori? This could be because of the missing image, but since he/she was not introduced earlier I did not understand the sentence very well.

**To Fix**
I cannot see the image in the /images directory, maybe it was already work in progress. In that case I'm sorry for the useless issue.

**Comment by misbach** [comment]
@GiovanniZotta PR #659 has been approved and merged. Do you mind verifying it fixes this issue and closing this issue?

**Comment by giovannizotta** [comment]
Thank you @misbach!
