### ISSUE TITLE
Discussing the structure of Chapter two

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#67]
@aantonop and I have discussed that the structure of the second chapter should be similar to the [one from Mastering Bitcoin](https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch02.asciidoc) but adapted to the topics of the lightning network. 

Reading through the second chapter of Mastering bitcoin we see that a user is getting a nice overview of most terms / concepts being used in bitcoin while staying with a rather simple example and a very end user oriented perspective. I tried to transfer this to lightning. I might have been a little bit too technical[ when you actually ready the bulletpoints that I also added to the section headers](https://github.com/lnbook/lnbook/commit/d83eba9dcdafbe3e5c495ecd91bfd5b96892fb1b) but I guess that is something that we will quickly figure out when we start writing everything. 

I am also not sure about the layer cake: https://blockstream.com/img/blog/2018-04-30/lightning-layers.png In general I like this separation of components a lot. My feeling is thought that we write from an end user perspective rather than the perspective of a BOLT developer. Still I wanted to throw in the layer cake:
```
multihop - SPHINX
transfer - HTLC
update - LN-Penalty / Eltoo / Gossip
base - framing - feature negotiation
transport - noise_xk
```

At this time I would be happy about your thoughts and comments. Maybe I should do a video in which I just discuss the two outlines and how I understand the content in them. Would that help to get ideas in or is video the wrong format to start such a discussion? 

in the follwing you can see the two structures

##  How Bitcoin Works
=== Transactions, Blocks, Mining, and the Blockchain
==== Bitcoin Overview
==== Buying a Cup of Coffee
=== Bitcoin Transactions
==== Transaction Inputs and Outputs
==== Transaction Chains
==== Making Change
==== Common Transaction Forms
=== Constructing a Transaction
==== Getting the Right Inputs
==== Creating the Outputs
==== Adding the Transaction to the Ledger
===== Transmitting the transaction
===== How it propagates
===== Bob's view
=== Bitcoin Mining
=== Mining Transactions in Blocks
=== Spending the Transaction

## How the Lightning Network Works
=== Payment channels
==== Multisig address
==== Funding Transaction
==== Commitment Transaction
==== Announcing the channel
==== closing the channel
=== Invoices
==== Payment Hash
==== Meta Data
=== Delivering the payment
==== Finding a path
==== Onion routing
==== Payment Forwarding Algorithm
=== Comparison with Bitcoin

## alternative structure for the invoice section
=== Invoices
==== create an invoice
==== decode an invoice
==== pay an invoice

**Comment by renepickhardt** [comment]
One day later I think there should be a subsection called "htlcs" or a "network of payment channels" . Maybe we could rename the last section "delivering a payment via a network of payment channels" and have a subsection explaining atomicity via a chain of htlcs. This could also be part of / complementary to onion routing

**Comment by timheide** [comment]
I really like the "Buying a Cup of Coffee" subsection in Mastering Bitcoin and I would love to see a subsection like that maybe with an updated example of the same use case. It would premature "Comparison with Bitcoin" a bit but I think it helps being introduced to a technical chapter by getting a real world example.

I like the overall structure of the chapter, well done. The list of bulletpoints looks very specific to me in comparison to Mastering Bitcoin where the whole chapter is roughly ~15 pages, so adding the layer cake to this chapter seems too early and complex. I would love to see it being explained later in the book.

**Comment by jachiang** [comment]
_Target Audience_
Hm, who is the user you mention above? I think this might be worth clarifying. A developer integrating lightning into an end-user app, or the actual app end-user? These would be two very different books.

_On the chapter sequence:_
* Payment channels
* Invoices
* Delivering the payment

You place invoices between payment channels and delivery(routing). I  feel there is a abstraction jump from payment channels up to invoices and then back to down to routing. Invoices make more sense once routing is covered. Of course, they can be introduced earlier as part of the "coffee purchase" experience (end-user pov).

_Comparison with Bitcoin:_
This feels like a chapter aimed at the end-user or a product manager considering what to do with this tech. Should I transact on-chain or off-chain? Otherwise, this seems like a proverbial comparison between apples and oranges.

**Comment by renepickhardt** [comment]
We have decided that the proposed outline for chapter two was too technical and moved it to chapter 03.
