### ISSUE TITLE
Flip images with temporal flow to have time on the x - axis

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#725]
https://github.com/lnbook/lnbook/blob/10e9f37ca885ac57373e94304f66b3a772699265/images/funding_message_flow.png has the time on the y axis from the top to the bottom. 

while this is consistent with the BOLTS it is actually very unnatural way to select the scale in this way. Maybe we diverge from the template in the BOLTs and flip it to have the temporal dependence on the x - axis from left to right which is more natural?

**Comment by aantonop** [comment]
This is standard practice for time-sequence protocol diagrams. I prefer we keep the standard.
