### ISSUE TITLE
Offering Illustrations, diagrams and more

### ISSUE THREAD

**Issue by Mjons** [lnbook/lnbook#8]
Hello,

My name is Michael, I am a content creator and marketer. I have been in blockchain since 2014. I produced the explainer video for Namecoin as well as others. I worked with Adam Levine on Tokenly. Currently I am working on a couple projects in the space: Tokensquare.com and Cone.io.

You can see some of my video work at reach.video

I am here to offer illustrations, diagrams and maye some support videos covering topics in the book to help promote it once it launches.

I am happy to collaborate with some of the experts here to fully understand and produce any visuals the book might need. so just let me know.

**Comment by renepickhardt** [comment]
Hey Michael thank your very much about your offer. 

I plan to create many more educational videos which will go along the book kind of like course work. for those videos I might be very delighted to have input in the forms of animations. 

as with graphics for the book I think that O'Reilly has a rather restrictive style guide and I think they will remake most of the graphics within their graphics department. That being said. I will certainly keep this issue open and we can see how things will work out once we are a little bit more concrete.

**Comment by dennisreimann** [comment]
Hey there, I just listened to Andreas' interview with Stephan Livera. He mentioned that community contributions to the book would be invited, so I'm just chiming in with these two articles of mine, which people seem to like.
In case they include explanations or diagrams that are helpful, just let me know:

- [The Payment Channel Lifecycle](https://d11n.net/lightning-network-payment-channel-lifecycle.html)
- [How channel capacity and liquidity affect payment routing](https://d11n.net/lightning-network-routing-payments-liquidity.html)

**Comment by ruevers** [comment]
> Hey there, I just listened to Andreas' interview with Stephan Livera. He mentioned that community contributions to the book would be invited, so I'm just chiming in with these two articles of mine, which people seem to like.


How expect the comunity ask help the people and change the mind to gain money, is a shame...

**Comment by ruevers** [comment]
> Hey Michael thank your very much about your offer.
> 
> I plan to create many more educational videos which will go along the book kind of like course work. for those videos I might be very delighted to have input in the forms of animations.
> 
> as with graphics for the book I think that O'Reilly has a rather restrictive style guide and I think they will remake most of the graphics within their graphics department. That being said. I will certainly keep this issue open and we can see how things will work out once we are a little bit more concrete.

is a open source book for comunit or something to you gain money in a publisher? I am litle confused now.

**Comment by renepickhardt** [comment]
hey @mjons and @dennisreimann I believe we allready have many diagrams but of course now where the text is finnishing you could check if you believe we are missing stuff. If so please feel free to add a PR with potential diagrams. Will close this issue for now!
