### ISSUE TITLE
Contribute to Chinese translation

### ISSUE THREAD

**Issue by anthonyhuanggr** [lnbook/lnbook#82]
Hi All:

We are one of well-known Blockchain We-Media community named "Lan hu bi ji (蓝狐笔记)" in China. 
We are existing that your guys working on writing a new book about Lightning Network. We agree that the off-chain Lighting network channel can speed up bitcoin to our daily life.

It will be great if we can contribute to translate this new Mastering the Lightning Network to Chinese users.

We have lots of experience in blockchain/bitcoin article and whitepaper translation. It will be great if we have a chance to contribute to Lightning Network.

Many thanks.

Anthony

**Comment by aantonop** [comment]
Community translation will not be possible until the license changes from CC-BY-NC-ND to CC-BY-SA which will only happen 12 months after publication (estimated Dec 2021).

However, if you work with a publisher in China, you can negotiate a license with O'Reilly Media.

**Comment by anthonyhuanggr** [comment]
Hi Andreas,

We are very interested in publishing this book in China, it will be great if you can share with me the contact person of  O'Reilly Media who I can negotiate a license with.
Many thanks.


Anthony
