### ISSUE TITLE
Fix needed [Typo] Chapter 8 – Fairness Protocol – Missing word "be" or tense adjustment

### ISSUE THREAD

**Issue by jnxdd** [lnbook/lnbook#847]
**Describe the error**
This phrase is grammatically incorrect "which is expected to active in Bitcoin in 2021."
Last line of fairness protocol (after pltcs).

**To Fix**
How should it be fixed?
Missing word "be" or wrong tense "activate" or "be activated"
+ which is expected to [be] active in Bitcoin in 2021."
+ which is expected to  [activate on] Bitcoin in 2021."
+ which is expected to  [be active on] Bitcoin in 2021."

**Additional context**
This paragraph
"Another proposed mechanism for implementing routing is a Point Time-Locked Contract (PTLC). PTLCs also achieve atomicity, trustless operation and multihop security, but do so with increased efficiency and better privacy. Efficient implementation of PTLCs depends on a new digital signature algorithm called Schnorr signatures, which is expected to active in Bitcoin in 2021."

**Comment by renepickhardt** [comment]
fixed
