### ISSUE TITLE
Chapter 7: Inconsistency between text and image

### ISSUE THREAD

**Issue by Fettelbield** [lnbook/lnbook#905]
**Describe the error**

In "_Constructing the Funding Transaction_" it says that "_Alice is spending a 200,000 satoshi output_" whereas the image **mtln_0704.png** shows a 100,000 satoshi output.

**How to fix**

Change the number "_100,000_" in **mtln_0704.png** to "_200,000_"

**Comment by aantonop** [comment]
Fixed, thanks
