### ISSUE TITLE
Technical depth of chapter 3

### ISSUE THREAD

**Issue by renepickhardt** [lnbook/lnbook#91]
When planning chapter 3 it was still chapter 2 (c.f. #67 ) but we decided that it seemed too technical for chapter 2. Now we moved it to chapter 3 to give a nice / rather technical overview of lightning. I started writing about multisig, P2SH and P2WSH (c.f. https://github.com/lnbook/lnbook/blob/4ed6de50ba61b91078387f1117235422ef5a40fa/ch03.asciidoc) but after a day I think this would already go to deep. I am currently thinking of still giving an overview of all the components / concepts of lightning but allow to blackbox. Just say it is a multisig address and refer to later chapters that would explain in detail to the last Byte what is happening. 

I think we will first have to transport an understanding of the important concepts and don't dive deep right away.

**Comment by chanhosuh** [comment]
How deep are you planning to go?  Code, say in Python?  

I think one thing I would have liked to see more of in "Mastering Bitcoin" was python code examples, and even some basic exercises filling in the blanks with the reader able to check their answers against simple unit tests.  I thought Jimmy Song's "Programming Bitcoin" was helpful in that regards, although I understand not wanting to go too far down that route.

If you think this is a good idea and would like a hand with say, Jupyter notebooks etc., I'd be happy to lend an assist.

**Comment by aantonop** [comment]
More detail and Python examples in later chapters, when we do the deeper
technical dive.
For chapter 3, I'd like to avoid going that deep yet.

>

**Comment by ImranLorgat** [comment]
Perhaps structure CH3 in the same way as CH2? Following Alice and Bob's LN Coffee payment, but explaining what's happening and the concepts at each point e.g. opening a channel, the mechanics of channels, funding transaction etc. without necessarily going into the code? Easier to follow when you're using a scaffolding the audience has just followed at a high level.

**Comment by aantonop** [comment]
Fixed in final edits of Chapter 3
