### ISSUE TITLE
does allow me to fork it and translate it into chinese?

### ISSUE THREAD

**Issue by Yihen-Liu** [lnbook/lnbook#923]
I prepare fork lnbook, and then translate it into Chinese, and synchronize it to the fork branch. At the same time, I reserve all the copyrights for you. It is only translated into Chinese. I hope that in the Chinese world, it can be used for the technology dissemination of the Lightning Network.  is it allowed to translate into Chinese?

**Comment by aantonop** [comment]
No, the CC-BY-NC-ND license does not allow translation.

In one year (Dec 2022) we hope to release under new license for
translation. Until then O'Reilly Media owns the rights to foreign
translation and can sell them exclusively.

**Comment by Yihen-Liu** [comment]
@aantonop  Thanks for your great job. see you later in Dec 2022.
