### ISSUE TITLE
Chapter 10, Figure 8: Wrong HTLCs amounts

### ISSUE THREAD

**Issue by timkaebisch** [lnbook/lnbook#976]
**Describe the error**
This issue is about the following section: Chapter 10, [Alice Selects the Path](https://github.com/lnbook/lnbook/blob/develop/10_onion_routing.asciidoc#alice-selects-the-path)

The first sentence reads: "From [[routing]](https://github.com/lnbook/lnbook/blob/develop/10_onion_routing.asciidoc#routing) we know that Alice will send a 50,000 satoshi payment to Dina via Bob and Chan. This payment is transmitted via a series of HTLCs, as shown in [Payment path with HTLCs from Alice to Dina](https://github.com/lnbook/lnbook/blob/develop/10_onion_routing.asciidoc#alice_dina_htlc_path)".

A 50.000 satoshi payment is mentioned, whereas the figure shows a 100.000 satoshi payment.

**To Fix**
Update the figure.

**Comment by azuchi** [comment]
This issue seems to be a duplicate #918 .

**Comment by timkaebisch** [comment]
Issue duplicates #918
