### ISSUE TITLE
Open Edition Soon?

### ISSUE THREAD

**Issue by SerafDosSantos** [lnbook/lnbook#996]
Hi @aantonop and all.

I translated **Mastering Bitcoin** and **Mastering Ethereum** in _French (Canada)_ on **Transifex** last year and was wondering when this one would be available for translation too.

Anytime soon?

**Comment by Yihen-Liu** [comment]
attention too

**Comment by aantonop** [comment]
License changing this week!

**Comment by aantonop** [comment]
License changed, see LICENSE.md and new README.md
